// ───────────────────────────────────────────────────────────────
// TEST: CONTINUE_SESSION Auto-Generation (T124)
// TEST: CONTINUE_SESSION.md Generation (T017-T020)
// ───────────────────────────────────────────────────────────────
// CHK-229: CONTINUE_SESSION auto-generated by generate-context.js
// T017-T020: Tests for session-manager generateContinueSessionMd()
'use strict';

const path = require('path');

/* ─────────────────────────────────────────────────────────────
   1. TEST CONFIGURATION
──────────────────────────────────────────────────────────────── */

const results = {
  passed: 0,
  failed: 0,
  skipped: 0,
  tests: [],
};

/* ─────────────────────────────────────────────────────────────
   2. TEST UTILITIES
──────────────────────────────────────────────────────────────── */

function log(msg) {
  console.log(msg);
}

function pass(testId, testName, evidence) {
  results.passed++;
  results.tests.push({ id: testId, name: testName, status: 'PASS', evidence });
  log(`   ✅ ${testId}: ${testName}`);
  if (evidence) log(`      Evidence: ${evidence}`);
}

function fail(testId, testName, reason) {
  results.failed++;
  results.tests.push({ id: testId, name: testName, status: 'FAIL', reason });
  log(`   ❌ ${testId}: ${testName}`);
  log(`      Reason: ${reason}`);
}

function skip(testId, testName, reason) {
  results.skipped++;
  results.tests.push({ id: testId, name: testName, status: 'SKIP', reason });
  log(`   ⏭️  ${testId}: ${testName} (skipped: ${reason})`);
}

/* ─────────────────────────────────────────────────────────────
   3. MODULE LOADING
──────────────────────────────────────────────────────────────── */

let collectSessionData;
let sessionManager;

try {
  const collectSessionDataPath = path.join(__dirname, '../../scripts/extractors/collect-session-data.js');
  collectSessionData = require(collectSessionDataPath);
  sessionManager = require('../lib/session/session-manager.js');
  pass('LOAD', 'Modules loaded successfully', 'collect-session-data.js and session-manager.js');
} catch (err) {
  fail('LOAD', 'Module loading failed', err.message);
  process.exit(1);
}

/* ─────────────────────────────────────────────────────────────
   4. T124: CONTINUE_SESSION AUTO-GENERATION TESTS
──────────────────────────────────────────────────────────────── */

function test_t124_determine_session_status() {
  log('\n🔬 T124: determine_session_status');

  const { determine_session_status } = collectSessionData;

  // T124-01: Returns BLOCKED when blockers exist
  try {
    const status = determine_session_status('Build failing due to missing dependency', [], 5);
    if (status === 'BLOCKED') {
      pass('T124-01', 'Returns BLOCKED when blockers exist', `status=${status}`);
    } else {
      fail('T124-01', 'Returns BLOCKED when blockers exist', `Expected BLOCKED, got ${status}`);
    }
  } catch (e) {
    fail('T124-01', 'Returns BLOCKED when blockers exist', e.message);
  }

  // T124-02: Returns IN_PROGRESS when blockers is "None"
  try {
    const status = determine_session_status('None', [], 5);
    if (status === 'IN_PROGRESS') {
      pass('T124-02', 'Returns IN_PROGRESS when blockers is "None"', `status=${status}`);
    } else {
      fail('T124-02', 'Returns IN_PROGRESS when blockers is "None"', `Expected IN_PROGRESS, got ${status}`);
    }
  } catch (e) {
    fail('T124-02', 'Returns IN_PROGRESS when blockers is "None"', e.message);
  }

  // T124-03: Returns COMPLETED when last observation indicates completion
  try {
    const observations = [
      { title: 'Initial setup', narrative: 'Started work' },
      { title: 'Final verification', narrative: 'All tests passed. Implementation complete!' }
    ];
    const status = determine_session_status('None', observations, 10);
    if (status === 'COMPLETED') {
      pass('T124-03', 'Returns COMPLETED when last observation indicates completion', `status=${status}`);
    } else {
      fail('T124-03', 'Returns COMPLETED when last observation indicates completion', `Expected COMPLETED, got ${status}`);
    }
  } catch (e) {
    fail('T124-03', 'Returns COMPLETED when last observation indicates completion', e.message);
  }

  // T124-04: Returns IN_PROGRESS with low message count
  try {
    const status = determine_session_status('None', [], 2);
    if (status === 'IN_PROGRESS') {
      pass('T124-04', 'Returns IN_PROGRESS with low message count', `status=${status}`);
    } else {
      fail('T124-04', 'Returns IN_PROGRESS with low message count', `Expected IN_PROGRESS, got ${status}`);
    }
  } catch (e) {
    fail('T124-04', 'Returns IN_PROGRESS with low message count', e.message);
  }
}

function test_t124_estimate_completion_percent() {
  log('\n🔬 T124: estimate_completion_percent');

  const { estimate_completion_percent } = collectSessionData;

  // T124-05: Returns 100 for COMPLETED status
  try {
    const percent = estimate_completion_percent([], 5, {}, 'COMPLETED');
    if (percent === 100) {
      pass('T124-05', 'Returns 100 for COMPLETED status', `percent=${percent}`);
    } else {
      fail('T124-05', 'Returns 100 for COMPLETED status', `Expected 100, got ${percent}`);
    }
  } catch (e) {
    fail('T124-05', 'Returns 100 for COMPLETED status', e.message);
  }

  // T124-06: Returns capped value for BLOCKED status
  try {
    const percent = estimate_completion_percent([], 20, {}, 'BLOCKED');
    if (percent <= 90) {
      pass('T124-06', 'Returns capped value for BLOCKED status', `percent=${percent} <= 90`);
    } else {
      fail('T124-06', 'Returns capped value for BLOCKED status', `Expected <= 90, got ${percent}`);
    }
  } catch (e) {
    fail('T124-06', 'Returns capped value for BLOCKED status', e.message);
  }

  // T124-07: Estimates based on message count and tool usage
  try {
    const toolCounts = { Write: 5, Edit: 3, Read: 10 };
    const observations = [{ title: 'test' }, { title: 'test2' }];
    const percent = estimate_completion_percent(observations, 10, toolCounts, 'IN_PROGRESS');
    if (percent > 0 && percent <= 95) {
      pass('T124-07', 'Estimates based on message count and tool usage', `percent=${percent}`);
    } else {
      fail('T124-07', 'Estimates based on message count and tool usage', `Expected 0 < percent <= 95, got ${percent}`);
    }
  } catch (e) {
    fail('T124-07', 'Estimates based on message count and tool usage', e.message);
  }

  // T124-08: Caps at 95% for IN_PROGRESS
  try {
    const toolCounts = { Write: 100, Edit: 100 };
    const observations = Array(20).fill({ title: 'obs' });
    const percent = estimate_completion_percent(observations, 50, toolCounts, 'IN_PROGRESS');
    if (percent <= 95) {
      pass('T124-08', 'Caps at 95% for IN_PROGRESS', `percent=${percent} <= 95`);
    } else {
      fail('T124-08', 'Caps at 95% for IN_PROGRESS', `Expected <= 95, got ${percent}`);
    }
  } catch (e) {
    fail('T124-08', 'Caps at 95% for IN_PROGRESS', e.message);
  }
}

function test_t124_build_continue_session_data() {
  log('\n🔬 T124: build_continue_session_data');

  const { build_continue_session_data } = collectSessionData;

  const baseParams = {
    observations: [],
    userPrompts: [{ prompt: 'Test', timestamp: new Date().toISOString() }],
    toolCounts: { Read: 5, Write: 2 },
    recentContext: [],
    FILES: [],
    SPEC_FILES: [],
    summary: 'Test session summary',
    projectPhase: 'IMPLEMENTATION',
    lastAction: 'Added feature',
    nextAction: 'Run tests',
    blockers: 'None',
    duration: '30m',
    decisionCount: 0
  };

  // T124-09: Returns all required fields
  try {
    const data = build_continue_session_data(baseParams);
    const requiredFields = ['SESSION_STATUS', 'COMPLETION_PERCENT', 'LAST_ACTIVITY_TIMESTAMP',
                           'SESSION_DURATION', 'CONTINUATION_COUNT', 'CONTEXT_SUMMARY',
                           'PENDING_TASKS', 'NEXT_CONTINUATION_COUNT', 'RESUME_CONTEXT'];
    const hasAll = requiredFields.every(f => data.hasOwnProperty(f));
    if (hasAll) {
      pass('T124-09', 'Returns all required fields', `fields: ${requiredFields.join(', ')}`);
    } else {
      const missing = requiredFields.filter(f => !data.hasOwnProperty(f));
      fail('T124-09', 'Returns all required fields', `Missing: ${missing.join(', ')}`);
    }
  } catch (e) {
    fail('T124-09', 'Returns all required fields', e.message);
  }

  // T124-10: Calculates continuation count correctly
  try {
    const params = { ...baseParams, recentContext: [{ continuationCount: 3 }] };
    const data = build_continue_session_data(params);
    if (data.CONTINUATION_COUNT === 3 && data.NEXT_CONTINUATION_COUNT === 4) {
      pass('T124-10', 'Calculates continuation count correctly', `count=${data.CONTINUATION_COUNT}, next=${data.NEXT_CONTINUATION_COUNT}`);
    } else {
      fail('T124-10', 'Calculates continuation count correctly', `Expected 3/4, got ${data.CONTINUATION_COUNT}/${data.NEXT_CONTINUATION_COUNT}`);
    }
  } catch (e) {
    fail('T124-10', 'Calculates continuation count correctly', e.message);
  }

  // T124-11: Defaults continuation count to 1
  try {
    const data = build_continue_session_data(baseParams);
    if (data.CONTINUATION_COUNT === 1 && data.NEXT_CONTINUATION_COUNT === 2) {
      pass('T124-11', 'Defaults continuation count to 1', `count=${data.CONTINUATION_COUNT}`);
    } else {
      fail('T124-11', 'Defaults continuation count to 1', `Expected 1/2, got ${data.CONTINUATION_COUNT}/${data.NEXT_CONTINUATION_COUNT}`);
    }
  } catch (e) {
    fail('T124-11', 'Defaults continuation count to 1', e.message);
  }

  // T124-12: Includes session duration
  try {
    const data = build_continue_session_data(baseParams);
    if (data.SESSION_DURATION === '30m') {
      pass('T124-12', 'Includes session duration', `duration=${data.SESSION_DURATION}`);
    } else {
      fail('T124-12', 'Includes session duration', `Expected 30m, got ${data.SESSION_DURATION}`);
    }
  } catch (e) {
    fail('T124-12', 'Includes session duration', e.message);
  }

  // T124-13: PENDING_TASKS is an array
  try {
    const data = build_continue_session_data(baseParams);
    if (Array.isArray(data.PENDING_TASKS)) {
      pass('T124-13', 'PENDING_TASKS is an array', `isArray=true, length=${data.PENDING_TASKS.length}`);
    } else {
      fail('T124-13', 'PENDING_TASKS is an array', `Got ${typeof data.PENDING_TASKS}`);
    }
  } catch (e) {
    fail('T124-13', 'PENDING_TASKS is an array', e.message);
  }

  // T124-14: Handles blocked session correctly
  try {
    const params = { ...baseParams, blockers: 'Missing API key for deployment' };
    const data = build_continue_session_data(params);
    if (data.SESSION_STATUS === 'BLOCKED' && data.COMPLETION_PERCENT <= 90) {
      pass('T124-14', 'Handles blocked session correctly', `status=${data.SESSION_STATUS}, percent=${data.COMPLETION_PERCENT}`);
    } else {
      fail('T124-14', 'Handles blocked session correctly', `status=${data.SESSION_STATUS}, percent=${data.COMPLETION_PERCENT}`);
    }
  } catch (e) {
    fail('T124-14', 'Handles blocked session correctly', e.message);
  }
}

/* ─────────────────────────────────────────────────────────────
   5. T017-T020: CONTINUE_SESSION.md GENERATION TESTS
──────────────────────────────────────────────────────────────── */

function test_t017_generate_continue_session_md() {
  log('\n🔬 T017: generateContinueSessionMd() creates valid markdown');

  const { generateContinueSessionMd } = sessionManager;

  // T017-01: Generates valid markdown with all required sections
  try {
    const sessionState = {
      sessionId: 'test-session-t017',
      specFolder: 'specs/003-memory/017-test',
      currentTask: 'T017',
      lastAction: 'Created test file',
      contextSummary: 'Testing markdown generation',
      pendingWork: 'Verify output structure',
      data: { progress: 50 }
    };
    const content = generateContinueSessionMd(sessionState);

    const hasHeader = content.includes('# CONTINUE SESSION');
    const hasSessionState = content.includes('## Session State');
    const hasContextSummary = content.includes('## Context Summary');
    const hasPendingWork = content.includes('## Pending Work');
    const hasQuickResume = content.includes('## Quick Resume');

    if (hasHeader && hasSessionState && hasContextSummary && hasPendingWork && hasQuickResume) {
      pass('T017-01', 'Generates valid markdown with all required sections', 'All sections present');
    } else {
      fail('T017-01', 'Generates valid markdown with all required sections', 'Missing sections');
    }
  } catch (e) {
    fail('T017-01', 'Generates valid markdown with all required sections', e.message);
  }

  // T017-02: Handles minimal session state (only sessionId)
  try {
    const minimalState = { sessionId: 'minimal-session' };
    const content = generateContinueSessionMd(minimalState);

    if (content.includes('# CONTINUE SESSION') && content.includes('minimal-session')) {
      pass('T017-02', 'Handles minimal session state (only sessionId)', 'Valid markdown generated');
    } else {
      fail('T017-02', 'Handles minimal session state (only sessionId)', 'Missing content');
    }
  } catch (e) {
    fail('T017-02', 'Handles minimal session state (only sessionId)', e.message);
  }

  // T017-03: Handles undefined sessionId gracefully
  try {
    const emptyState = {};
    const content = generateContinueSessionMd(emptyState);

    if (content.includes('# CONTINUE SESSION') && content.includes('N/A')) {
      pass('T017-03', 'Handles undefined sessionId gracefully', 'N/A placeholders used');
    } else {
      fail('T017-03', 'Handles undefined sessionId gracefully', 'Missing N/A placeholders');
    }
  } catch (e) {
    fail('T017-03', 'Handles undefined sessionId gracefully', e.message);
  }

  // T017-04: Includes horizontal rule separators between sections
  try {
    const sessionState = { sessionId: 'test-separators', contextSummary: 'Test content' };
    const content = generateContinueSessionMd(sessionState);

    const hrCount = (content.match(/^---$/gm) || []).length;
    if (hrCount >= 3) {
      pass('T017-04', 'Includes horizontal rule separators between sections', `hrCount=${hrCount}`);
    } else {
      fail('T017-04', 'Includes horizontal rule separators between sections', `Expected >= 3, got ${hrCount}`);
    }
  } catch (e) {
    fail('T017-04', 'Includes horizontal rule separators between sections', e.message);
  }
}

function test_t018_session_state_table() {
  log('\n🔬 T018: Session state table is included in generated markdown');

  const { generateContinueSessionMd } = sessionManager;

  // T018-01: Includes session state table with all fields
  try {
    const sessionState = {
      sessionId: 'table-test-session',
      specFolder: 'specs/test-folder',
      currentTask: 'T018',
      lastAction: 'Testing table generation'
    };
    const content = generateContinueSessionMd(sessionState);

    const hasTable = content.includes('| Field | Value |') && content.includes('|-------|-------|');
    const hasFields = content.includes('**Session ID**') && content.includes('**Spec Folder**');

    if (hasTable && hasFields) {
      pass('T018-01', 'Includes session state table with all fields', 'Table structure correct');
    } else {
      fail('T018-01', 'Includes session state table with all fields', 'Missing table or fields');
    }
  } catch (e) {
    fail('T018-01', 'Includes session state table with all fields', e.message);
  }

  // T018-02: Displays sessionId in code format
  try {
    const sessionState = { sessionId: 'code-format-test' };
    const content = generateContinueSessionMd(sessionState);

    if (content.includes('`code-format-test`')) {
      pass('T018-02', 'Displays sessionId in code format', 'Backticks present');
    } else {
      fail('T018-02', 'Displays sessionId in code format', 'Missing backticks');
    }
  } catch (e) {
    fail('T018-02', 'Displays sessionId in code format', e.message);
  }

  // T018-03: Shows Active as status
  try {
    const sessionState = { sessionId: 'status-test' };
    const content = generateContinueSessionMd(sessionState);

    if (content.includes('| **Status** | Active |')) {
      pass('T018-03', 'Shows Active as status', 'Status=Active');
    } else {
      fail('T018-03', 'Shows Active as status', 'Missing Active status');
    }
  } catch (e) {
    fail('T018-03', 'Shows Active as status', e.message);
  }

  // T018-04: Includes ISO timestamp in Updated field
  try {
    const sessionState = { sessionId: 'timestamp-test' };
    const content = generateContinueSessionMd(sessionState);

    const hasTimestamp = /\| \*\*Updated\*\* \| \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/.test(content);
    if (hasTimestamp) {
      pass('T018-04', 'Includes ISO timestamp in Updated field', 'ISO format present');
    } else {
      fail('T018-04', 'Includes ISO timestamp in Updated field', 'Missing timestamp');
    }
  } catch (e) {
    fail('T018-04', 'Includes ISO timestamp in Updated field', e.message);
  }

  // T018-05: Table values reflect provided session state
  try {
    const sessionState = {
      sessionId: 'values-test-001',
      specFolder: 'specs/my-spec-folder',
      currentTask: 'TASK-123',
      lastAction: 'Completed implementation'
    };
    const content = generateContinueSessionMd(sessionState);

    const hasAll = content.includes('values-test-001') &&
                   content.includes('specs/my-spec-folder') &&
                   content.includes('TASK-123') &&
                   content.includes('Completed implementation');
    if (hasAll) {
      pass('T018-05', 'Table values reflect provided session state', 'All values present');
    } else {
      fail('T018-05', 'Table values reflect provided session state', 'Missing values');
    }
  } catch (e) {
    fail('T018-05', 'Table values reflect provided session state', e.message);
  }
}

function test_t019_context_summary() {
  log('\n🔬 T019: Context summary is included in generated markdown');

  const { generateContinueSessionMd } = sessionManager;

  // T019-01: Includes Context Summary section
  try {
    const sessionState = {
      sessionId: 'context-test',
      contextSummary: 'Working on crash recovery implementation'
    };
    const content = generateContinueSessionMd(sessionState);

    if (content.includes('## Context Summary') && content.includes('Working on crash recovery implementation')) {
      pass('T019-01', 'Includes Context Summary section', 'Context present');
    } else {
      fail('T019-01', 'Includes Context Summary section', 'Missing context');
    }
  } catch (e) {
    fail('T019-01', 'Includes Context Summary section', e.message);
  }

  // T019-02: Shows placeholder when contextSummary is not provided
  try {
    const sessionState = { sessionId: 'no-context-test' };
    const content = generateContinueSessionMd(sessionState);

    if (content.includes('## Context Summary') && content.includes('_No context summary available._')) {
      pass('T019-02', 'Shows placeholder when contextSummary is not provided', 'Placeholder present');
    } else {
      fail('T019-02', 'Shows placeholder when contextSummary is not provided', 'Missing placeholder');
    }
  } catch (e) {
    fail('T019-02', 'Shows placeholder when contextSummary is not provided', e.message);
  }

  // T019-03: Includes Pending Work section
  try {
    const sessionState = {
      sessionId: 'pending-work-test',
      pendingWork: 'Write tests for T017-T020'
    };
    const content = generateContinueSessionMd(sessionState);

    if (content.includes('## Pending Work') && content.includes('Write tests for T017-T020')) {
      pass('T019-03', 'Includes Pending Work section', 'Pending work present');
    } else {
      fail('T019-03', 'Includes Pending Work section', 'Missing pending work');
    }
  } catch (e) {
    fail('T019-03', 'Includes Pending Work section', e.message);
  }

  // T019-04: Shows placeholder when pendingWork is not provided
  try {
    const sessionState = { sessionId: 'no-pending-test' };
    const content = generateContinueSessionMd(sessionState);

    if (content.includes('## Pending Work') && content.includes('_No pending work recorded._')) {
      pass('T019-04', 'Shows placeholder when pendingWork is not provided', 'Placeholder present');
    } else {
      fail('T019-04', 'Shows placeholder when pendingWork is not provided', 'Missing placeholder');
    }
  } catch (e) {
    fail('T019-04', 'Shows placeholder when pendingWork is not provided', e.message);
  }

  // T019-05: Includes Additional State Data section when data is provided
  try {
    const sessionState = {
      sessionId: 'data-test',
      data: { tasksCompleted: ['T001', 'T002'], progress: 75 }
    };
    const content = generateContinueSessionMd(sessionState);

    const hasSection = content.includes('## Additional State Data');
    const hasJson = content.includes('```json') && content.includes('"progress": 75');

    if (hasSection && hasJson) {
      pass('T019-05', 'Includes Additional State Data section when data is provided', 'Data section present');
    } else {
      fail('T019-05', 'Includes Additional State Data section when data is provided', 'Missing data section');
    }
  } catch (e) {
    fail('T019-05', 'Includes Additional State Data section when data is provided', e.message);
  }

  // T019-06: Excludes Additional State Data section when data is not provided
  try {
    const sessionState = { sessionId: 'no-data-test', contextSummary: 'Some context' };
    const content = generateContinueSessionMd(sessionState);

    if (!content.includes('## Additional State Data')) {
      pass('T019-06', 'Excludes Additional State Data section when data is not provided', 'Section excluded');
    } else {
      fail('T019-06', 'Excludes Additional State Data section when data is not provided', 'Section present unexpectedly');
    }
  } catch (e) {
    fail('T019-06', 'Excludes Additional State Data section when data is not provided', e.message);
  }
}

function test_t020_quick_resume_command() {
  log('\n🔬 T020: Quick resume command is correctly formatted');

  const { generateContinueSessionMd } = sessionManager;

  // T020-01: Generates /spec_kit:resume command when specFolder is provided
  try {
    const sessionState = {
      sessionId: 'resume-cmd-test',
      specFolder: 'specs/003-memory/020-test'
    };
    const content = generateContinueSessionMd(sessionState);

    if (content.includes('## Quick Resume') && content.includes('/spec_kit:resume specs/003-memory/020-test')) {
      pass('T020-01', 'Generates /spec_kit:resume command when specFolder is provided', 'Command present');
    } else {
      fail('T020-01', 'Generates /spec_kit:resume command when specFolder is provided', 'Missing command');
    }
  } catch (e) {
    fail('T020-01', 'Generates /spec_kit:resume command when specFolder is provided', e.message);
  }

  // T020-02: Generates memory_search command with sessionId when specFolder is not provided
  try {
    const sessionState = { sessionId: 'session-only-test' };
    const content = generateContinueSessionMd(sessionState);

    if (content.includes('## Quick Resume') && content.includes('memory_search({ sessionId: "session-only-test" })')) {
      pass('T020-02', 'Generates memory_search command with sessionId when specFolder is not provided', 'Command present');
    } else {
      fail('T020-02', 'Generates memory_search command with sessionId when specFolder is not provided', 'Missing command');
    }
  } catch (e) {
    fail('T020-02', 'Generates memory_search command with sessionId when specFolder is not provided', e.message);
  }

  // T020-03: Generates generic memory_search when neither specFolder nor sessionId is provided
  try {
    const sessionState = {};
    const content = generateContinueSessionMd(sessionState);

    if (content.includes('## Quick Resume') && content.includes('memory_search({ query: "last session" })')) {
      pass('T020-03', 'Generates generic memory_search when neither specFolder nor sessionId is provided', 'Command present');
    } else {
      fail('T020-03', 'Generates generic memory_search when neither specFolder nor sessionId is provided', 'Missing command');
    }
  } catch (e) {
    fail('T020-03', 'Generates generic memory_search when neither specFolder nor sessionId is provided', e.message);
  }

  // T020-04: Resume command is wrapped in code block
  try {
    const sessionState = { sessionId: 'code-block-test', specFolder: 'specs/test' };
    const content = generateContinueSessionMd(sessionState);

    const quickResumeIndex = content.indexOf('## Quick Resume');
    const sectionContent = content.slice(quickResumeIndex, quickResumeIndex + 300);
    const backtickMatches = sectionContent.match(/```/g);

    if (backtickMatches && backtickMatches.length >= 2) {
      pass('T020-04', 'Resume command is wrapped in code block', `backticks=${backtickMatches.length}`);
    } else {
      fail('T020-04', 'Resume command is wrapped in code block', 'Missing code block');
    }
  } catch (e) {
    fail('T020-04', 'Resume command is wrapped in code block', e.message);
  }

  // T020-05: specFolder takes precedence over sessionId for resume command
  try {
    const sessionState = {
      sessionId: 'both-provided-session',
      specFolder: 'specs/priority-test'
    };
    const content = generateContinueSessionMd(sessionState);

    const hasSpec = content.includes('/spec_kit:resume specs/priority-test');
    const noMemorySearch = !content.includes('memory_search({ sessionId: "both-provided-session" })');

    if (hasSpec && noMemorySearch) {
      pass('T020-05', 'specFolder takes precedence over sessionId for resume command', 'Correct precedence');
    } else {
      fail('T020-05', 'specFolder takes precedence over sessionId for resume command', 'Wrong precedence');
    }
  } catch (e) {
    fail('T020-05', 'specFolder takes precedence over sessionId for resume command', e.message);
  }
}

/* ─────────────────────────────────────────────────────────────
   6. TEST RUNNER
──────────────────────────────────────────────────────────────── */

function runTests() {
  log('═══════════════════════════════════════════════════════════');
  log('  CONTINUE_SESSION.md Generation Tests (T017-T020, T124)');
  log('═══════════════════════════════════════════════════════════');

  // T124 tests
  test_t124_determine_session_status();
  test_t124_estimate_completion_percent();
  test_t124_build_continue_session_data();

  // T017-T020 tests
  test_t017_generate_continue_session_md();
  test_t018_session_state_table();
  test_t019_context_summary();
  test_t020_quick_resume_command();

  // Summary
  log('\n═══════════════════════════════════════════════════════════');
  log('  RESULTS');
  log('═══════════════════════════════════════════════════════════');
  log(`   ✅ Passed:  ${results.passed}`);
  log(`   ❌ Failed:  ${results.failed}`);
  log(`   ⏭️  Skipped: ${results.skipped}`);
  log(`   📊 Total:   ${results.passed + results.failed + results.skipped}`);
  log('═══════════════════════════════════════════════════════════');

  if (results.failed > 0) {
    log('\n⚠️  Some tests failed. Review output above.');
    process.exit(1);
  } else {
    log('\n✅ ALL TESTS PASSED');
    process.exit(0);
  }
}

// Run tests
runTests();
